DDL OLAP
1
CREATE TABLE REGION (
    -> REGION_ID INT NOT NULL,
    -> REGION_NAME VARCHAR(20) NOT NULL,
    -> PRIMARY KEY (REGION_ID))
    -> ENGINE = InnoDB;


2
CREATE TABLE SUBREGION(
SUBREGION_ID INT NOT NULL,
SUBREGION_NAME VARCHAR(30) NOT NULL,
REGION_ID INT NOT NULL,
PRIMARY KEY (SUBREGION_ID, REGION_ID),
INDEX fk_SUBREGION_REGION_idx (REGION_ID ASC) VISIBLE, CONSTRAINT fk_SUBREGION_REGION
FOREIGN KEY (REGION_ID)
REFERENCES REGION(REGION_ID) ON DELETE NO ACTION
 
ON UPDATE NO ACTION) ENGINE = InnoDB;

3
CREATE TABLE WAREHOUSE(
CODE INT NOT NULL,
SUBREGION_ID INT NOT NULL,
PRIMARY KEY (CODE, SUBREGION_ID),
INDEX fk_WAREHOUSE_SUBREGION1_idx (SUBREGION_ID ASC) VISIBLE,
CONSTRAINT fk_WAREHOUSE_SUBREGION1
FOREIGN KEY (SUBREGION_ID)
REFERENCES SUBREGION(SUBREGION_ID) ON DELETE NO ACTION
ON UPDATE NO ACTION) ENGINE = InnoDB;

4
CREATE TABLE BOOKS(
ISBN INT NOT NULL,
TITLE VARCHAR(45) NULL,
PRICE VARCHAR(45) NULL, 
PRIMARY KEY (ISBN))
ENGINE = InnoDB;

5
CREATE TABLE YEAR(
YEAR_ID INT NOT NULL,
YEAR YEAR(4) NULL, PRIMARY KEY (YEAR_ID))
ENGINE = InnoDB;

6
CREATE TABLE MONTH(
MONTH_ID INT NOT NULL,
MONTH VARCHAR(15) NULL,
YEAR_ID INT NOT NULL,
PRIMARY KEY (MONTH_ID,YEAR_ID),
INDEX fk_MONTH_YEAR1_idx (YEAR_ID ASC) VISIBLE,
CONSTRAINT fk_MONTH_YEAR1 FOREIGN KEY(YEAR_ID)
REFERENCES YEAR(YEAR_ID) ON DELETE NO ACTION
ON UPDATE NO ACTION) ENGINE = InnoDB;

7
CREATE TABLE DAY(
NUM_DAY INT NOT NULL,
DAY_ID VARCHAR(45) NOT NULL,
MONTH_ID INT NOT NULL,
PRIMARY KEY (DAY_ID, MONTH_ID),
INDEX fk_DAY_MONTH1_idx (MONTH_ID ASC) VISIBLE, 
CONSTRAINT fk_DAY_MONTH1
FOREIGN KEY (MONTH_ID)
REFERENCES MONTH(MONTH_ID) ON DELETE NO ACTION
ON UPDATE NO ACTION) ENGINE = InnoDB;



8
CREATE TABLE FACTS_TICKET(
SELL_BY_PRODUCT DOUBLE NOT NULL,
TICKET_NUMBER INT NOT NULL,
BOOKS_ISBN INT NOT NULL,
WAREHOUSE_CODE INT NOT NULL,
DAY_ID VARCHAR(45) NOT NULL,
PRIMARY KEY (SELL_BY_PRODUCT, BOOKS_ISBN, WAREHOUSE_CODE,
DAY_ID),
INDEX fk_FACTS_TICKET_BOOKS1_idx (BOOKS_ISBN ASC) VISIBLE, INDEX fk_FACTS_TICKET_WAREHOUSE1_idx (WAREHOUSE_CODE ASC),
INDEX fk_FACTS_TICKET_DAY1_idx (DAY_ID ASC) ,
CONSTRAINT fk_FACTS_TICKET_BOOKS1
FOREIGN KEY (BOOKS_ISBN)
REFERENCES BOOKS(ISBN) ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT fk_FACTS_TICKET_WAREHOUSE1 
FOREIGN KEY(WAREHOUSE_CODE)
REFERENCES WAREHOUSE(CODE) ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT fk_FACTS_TICKET_DAY1
FOREIGN KEY (DAY_ID)
REFERENCES DAY(DAY_ID) ON DELETE NO ACTION
ON UPDATE NO ACTION) ENGINE = InnoDB;


